### ISSUE TITLE
Redeclaring the autoload function

### ISSUE THREAD

**Issue by mbopp** [symfonycorp/platformsh-symfony-template#11]
I am getting the following error a few times a day-ish as shown in the attached log output. 

```
PHP Fatal error:  Cannot redeclare composerRequire4e7f5470b97bd5f9409a7fc8de0ad87e() (previously declared in /app/vendor/composer/autoload_real.php:57) in /app/vendor/composer/autoload_real.php on line 57
```

My `.platform.app.yaml` is configured just as the template in this project with the addition of the following PHP variables: 

```
        opcache.preload: /app/config/preload.php
        opcache.memory_consumption: 64
        opcache.max_accelerated_files: 20000
        opcache.validate_timestamps: 0
```

Any idea what might be causing the `autoload_real.php` file to be included more than once?

**Comment by mbopp** [comment]
I have confirmed this is a result of `opcache`. Where the actual 'bug' lies is another question. For the time being I will not use opcache to prevent this recurring issue. 

FWIW. I did try the opcache property of `dups_fix` which is referenced in documenation https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.dups-fix . It seemed promising, but did not correct the issue.

**Comment by fabpot** [comment]
I've no idea what this occurs, but it does not seem related to Platform.sh or these templates. FWIW, I have never had such an issue (yet).
