### ISSUE TITLE
Expand the README

### ISSUE THREAD

**Issue by tacman** [symfonycorp/platformsh-symfony-template#7]
For the love of all that good and holy and right, please provide some guidance on how to use this.

This page, on platform.sh is, well, kinda sparse:

https://docs.platform.sh/frameworks/symfony.html
![image](https://user-images.githubusercontent.com/619585/149429639-bef7201e-efde-4ea1-9780-43575308afaf.png)

It links to a read-only repo that is likely deprecated (when something says, don't use this, use something else): 
 https://github.com/platformsh-templates/symfony5

![image](https://user-images.githubusercontent.com/619585/149429977-fffb316a-85d8-44a5-9eb8-aa5b1411aea3.png)

And the something else this!  

I'm trying to migrate from SymfonyCloud, and looking for documentation on how to proceed.  I've run the automated migration, and the code has migrated, I was hoping to find some documentation here on how to configure platform.sh to run Symfony projects, in particular redis, postgres, etc, and integrating the environment variables into the app. 

Thanks.

**Comment by fabpot** [comment]
Long story short: if you are migrating a project from SymfonyCloud to Platform.sh, you will get the same experience on both platforms if you keep using the SymfonyCloud configurator in your .platform.app.yaml file (with the symfony-build and symfony-deploy scripts). Env vars are going to be automatically defined like on SymfonyCloud, the same goes for services. The only difference that is not taken care of by the project:migrate command is that you need to rename SYMFONY_BRANCH to PLATFORM_BRANCH in .platform.app.yaml if you are using it.

If you need anything else, please feel free to ping me or Nicolas on Slack.

**Comment by flovntp** [comment]
Hi all, 
Don't know if it feet with this issue but i create a pull request to add more info in the README file 
https://github.com/symfonycorp/platformsh-symfony-template/pull/12
hope it helps. 

ps: for viewing it in a readable manner, please follow this link https://github.com/flovntp/platformsh-symfony-template/tree/fix/readme
